added hover effect to collections
dashersw/mogollar pull request #20
Opened 2020-08-21 16:14 UTC by berkbaski

i noticed when first look. collections did not have cursor property. i was add this and hover effect for collections. (nice to have)

# Before
![before](https://user-images.githubusercontent.com/25839586/90911352-8bc03e00-e3e1-11ea-9f49-53fb5daf4138.gif)

# After
![after](https://user-images.githubusercontent.com/25839586/90911448-ab576680-e3e1-11ea-8319-e211655d8390.gif)

2020-08-21 16:20 UTC, dashersw commented
Hello @berkbaski ! Thank you for the PR, this was much needed! Canonically, a hover "highlights" an element. In this case the hovered element is turning darker. How could we fix this?

2020-08-21 16:25 UTC, berkbaski commented
Sorry @dashersw. I don't understand (my fault ... 🙁 ) can you provide more details?

2020-08-21 16:27 UTC, dashersw commented
A gray element, when hovered, turns white. A black element, when hovered, turns gray. A navy blue element, when hovered, turns bright blue. A dark green turns a bright green. In this case a white element is turning gray :) So that's the opposite of what the hover effect should be. How can we change this?

2020-08-21 20:41 UTC, berkbaski commented
@dashersw i found this solution. i'm not sure for colors. 😶

2020-08-23 18:42 UTC, dashersw requested changes

2020-08-23 18:42 UTC, dashersw commented on src/components/connections.vue
> +  color: var(--list-hover-color);
Yeah this was also what I had in mind. I hope it works.

2020-08-23 18:42 UTC, dashersw commented on src/components/connections.vue
> +  transition: var(--transition);
You need to move `transition` to `.collection`, otherwise it won’t transition when you hover off.

2020-08-23 18:42 UTC, dashersw commented on src/components/connections.vue
> +const connectionName = "localhost";
Please make sure you remove this styling change. We use single quotes.

2020-08-23 18:42 UTC, dashersw commented on src/assets/theme.css
> +  --list-hover-color: #bcbcbc;
Just need to make sure this is not too dark. Although, it’s not list-hover-color anymore. Let’s call it `dim`.

2020-08-23 22:52 UTC, berkbaski commented
hi @dashersw, eslint on my computer made me sad :(
thank you for your patience and kindness.

2020-08-29 11:45 UTC, dashersw approved these changes

2020-08-29 11:48 UTC, merged